[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/unite.vim.git'

[[plugins]]
repo = 'Shougo/neomru.vim.git'

[[plugins]]
repo = 'Yggdroot/indentLine'
